before_script:
  - apt-get update -qq && apt-get install -y -qq python3-numpy python3-scipy > /dev/null


test:
  script:
    - export CWD=${PWD}
    - cd ../
    - export PYTHONPATH=${PWD}
    - echo ${PYTHONPATH}
    - cd ${CWD}
    - make test
